services:
  - type: web
    name: affinityx-ai-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_API_URL
        sync: false
    healthCheckPath: /
